#!/bin/bash
filename=$1
intp=""
ext="${1#*.}"
function skedush () {
if [[ "$ext" = "sh" ]];then 
  intp="#!/bin/bash"
elif [[ "$ext" = "py" ]];then
  intp="#!/bin/env python3"
else 
  intp=""
fi
echo $intp
}

val=$(skedush)
echo $val
found="$(find . -type f -name $filename)"
echo "$found"
if [[ "$found" == *"$filename"* ]];then
  echo "File already exists.."
else
  touch "$filename"
  echo "$intp" > $1
  chmod 700 "$filename"
  alias vim="nvim"
  vim "$filename"
fi

